app:
  name: "Watermark Remover Suite"
  version: "0.1.0"

paths:
  default_output_dir: "dist/processed"
  logs_dir: "verification_reports/logs"

image_processing:
  inpaint_radius: 3
  inpaint_method: "telea"
  detection:
    method: "threshold"
    threshold: 230
    dilate_iterations: 2
    blur_kernel: 5

video_processing:
  reuse_mask: true
  preserve_audio: true
  codec: "libx264"
  audio_codec: "aac"
  bitrate: null
  auto_mask:
    threshold: 230
    dilate_iterations: 2
    blur_kernel: 5

batch:
  max_workers: 2
  halt_on_error: false

logging:
  level: "INFO"
  console:
    enabled: true
    format: "%(levelname)s | %(name)s | %(message)s"
  file:
    enabled: true
    filename: "verification_reports/logs/watermark_remover.log"
    format: "%(asctime)s | %(levelname)s | %(name)s | %(message)s"
    rotate_bytes: 1048576
    backups: 5
